apiVersion: apps/v1
kind: Deployment
metadata:
  name: bubble
  labels:
    app: bubble
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bubble
  template:
    metadata:
      labels:
        app: bubble
        tier: bubble
    spec:
      containers:
      - name: bubble
        image: ddolly518/bubble:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: bubble
---
apiVersion: v1
kind: Service
metadata:
  name: bubble
  labels:
    app: bubble
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: 3team
    tier: 3team
  type: LoadBalancer
