apiVersion: apps/v1
kind: Deployment
metadata:
  name: bubble
  labels:
    app: bubble
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bubble
  template:
    metadata:
      labels:
        app: bubble
        tier: bubble
    spec:
      containers:
      - name: bubble
        image: ddolly518/bubble:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: bubble
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PW
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_HOST
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_USER
        - name: RABBITMQ_PW
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_PW
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: bubble
  labels:
    app: bubble
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: bubble
    tier: bubble
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
    template:
      metadata:
        labels:
          app: rabbitmq
      spec:
        containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
          - containerPort: 5672
          - containerPort: 15672
          env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_USER
          - name: RABBITMQ_DEFAULT_PW
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_PW
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    name: http
  selector:
    app: rabbitmq
  type: ClusterIP
